# Generated by Django 4.2.1 on 2023-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(max_length=45),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=6),
        ),
    ]
