# Generated by Django 4.2.1 on 2023-06-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_telefono_alter_empleado_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', default=0, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_boleta',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(db_column='rut_cliente', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
