# Generated by Django 4.2.1 on 2023-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_boleta_email_remove_boleta_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='db_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_boleta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
