# Generated by Django 4.2.1 on 2023-06-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_imagen_alter_boleta_id_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
