# Generated by Django 4.2.1 on 2023-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
