# Generated by Django 4.2.1 on 2023-06-21 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_producto_id_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='rut_cliente',
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
