# Generated by Django 4.2.1 on 2023-06-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_boleta_rut_cliente_boleta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='app/static/'),
        ),
    ]
